### ISSUE TITLE
Tugboat simulation

### ISSUE THREAD

**Issue by mzahana** [srmainwaring/asv_wave_sim#48]
Hi!

Thank you gor this great project.

I have a project where I need to simulate a tugboat with a propulsion system.

Is there any tutorial that could walk me through the required customization steps?

Would the the hydrodynamic plugin in this project be good enough to use in this case? Or I need to implement a different one?

I also believe that I would need to implement a thruster model, right?
Would the one in the VRX project ( https://github.com/osrf/vrx/blob/master/usv_gazebo_plugins/src/usv_gazebo_thrust_plugin.cc ) work ?

Any hints are highly appreciated.

Thanks.

**Comment by srmainwaring** [comment]
Hi @mzahana, there is no separate tutorial as such, but there are some examples which may help.

For a guide on setting a model up with a thruster I'd suggest looking at the WAM-V model in the `gz-ignition` branch. (I'm planning to make this branch for [Gazebo Garden](https://gazebosim.org/docs/garden) the default ('master`) and put the current version for Gazebo 9 into archive).

The [wam-v model](https://github.com/srmainwaring/asv_wave_sim/tree/gz-marine/gz-marine-models/models/wam-v) uses the Gazebo thruster plugin. I've used ArduPilot for control, but you could use ROS if you prefer - they key is to have some system publishing to the required `gz-transport` topic.

The hydrodynamics plugin included in this project may be enough. Alternatively you can disable the drag components keeping only the buoyancy, then use the hydrodynamics plugin included in Gazebo Garden. I'd suggest experimenting with both to find the best fit for your requirements.

The other work required is simplifying the collision mesh for the model. I use Blender for this and there are some brief notes describing the procedure in the [attached presentation here](https://community.gazebosim.org/t/community-meeting-maritime-jun-2022). The approach is to remove highly detailed mesh features then use the decimate modifier to reduce the vertex count. You could alternatively stack together a number of collision primitives to approximate the the vessel volume instead of using a mesh - I have not tried this but it may be a quicker method to get going.
