### ISSUE TITLE
gazebo11 with fft_waves branch

### ISSUE THREAD

**Issue by esharet** [srmainwaring/asv_wave_sim#92]
Hi,
First, thank you for your projects! I am trying to clone your branch fft_waves with gazebo11. everything works ok but the ocean model is crushing. the error I get is libOceanVisualPlugin.so: undefined symbol: _ZN6gazebo9rendering10AttachMeshERNS0_6VisualERKNSt7__cxx111basic_stringIcSt11char_traitsIcESaIcEEESA_bSA_

when I check it with c++filt I get:
gazebo::rendering::AttachMesh(gazebo::rendering::Visual&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)

can you please help me fix it?

**Comment by srmainwaring** [comment]
Hi @esharet, thanks for your interest. Support for Gazebo9 and Gazebo11 is maintenance now as the development focus is on the new gazebo versions available from https://gazebosim.org/home.

The error suggests you may have built against the gazebo9 libs rather than gazebo11, but it's hard to tell without more information. Could you please provide some system info:

Ubuntu version:

```bash
lsb_release -a
```

Gazebo packages:

```
apt list --installed | grep gazebo
```

Gazebo version:

```
gazebo --version
```

**Comment by esharet** [comment]
It works, 
Thank you
